services:
  hospitalv2:
    container_name: hospitalv2
    build:
      context: ./
      dockerfile: Dockerfile
    image: techwire/hospitalv2:1.5.0
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_Kestrel__Certificates__Default__Password=RAVIndu751
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ./https:/https:ro
    depends_on:
      - hospitalv2-api
  
  hospitalv2-api:
    container_name: hospitalv2-api
    build:
      context: ./
      dockerfile: Dockerfile.api
    image: techwire/hospitalv2-api:1.5.0
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - ASPNETCORE_URLS=https://+:8443;http://+:8080
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_Kestrel__Certificates__Default__Password=RAVIndu751
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ./https:/https:ro

volumes:
  certs: